#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPTS_DIR="$CURRENT_DIR/../scripts"

source "$SCRIPTS_DIR/tmux_options.sh"
source "$SCRIPTS_DIR/display_icon.sh"

main (){
    set_tmux_option "prefix" "None"
    set_tmux_option "key-table" "off"
    tmux if-shell -F '#{pane_in_mode}' 'send-keys -X cancel'
    tmux refresh-client -S 
    display_icon
}
main
